### ISSUE TITLE
Manipulation of file name

### ISSUE THREAD

**Issue by doguhanokumus** [peyo/rget-jsftp#1]
Hey there,

While downloading a folder, with all files within, can we manipulate the target file name?
Such as: adding a prefix, lower- or uppercasing all the letters?

Reason: Some files on the source have ".JPG" extension and some have ".jpg" extension, differing in case, and I'd like to manage them via context.

I see that there are some events and I can handle it after the download is finished, but I'd rather resolve it before or during the download process, to not to access the files twice, and not to dupe on the next run.

Thank you.

**Comment by doguhanokumus** [comment]
For now, I'll be overriding the function.

```javascript
var ctx = rgetClient.generateDownloadContext(".", "./downloads");
ctx.getFileDestination = function(file){
  var filename = (file.relativePath === '' ? file.name.toUpperCase() 
                                           : file.relativePath.toUpperCase());
  return path.normalize(path.join(ctx.destination, filename));
}
```

**Comment by peyo** [comment]
Hi,

Your method seems work but it's an overwriting.

I prefer modify the context generator so that it takes in the parameter named "to", a "string" or a "function".

This function will be used for generate the file destination path. 
That function will have one parameter : the file object and will return a "string" : the filesystem path.

It's good for you ?

Thank you
Pierre

**Comment by doguhanokumus** [comment]
Awesome news, yes preferebly a function parameter would be great.

Thank you.

**Comment by peyo** [comment]
Hello,
I realese a new version : 0.1.4.
Now it's possible to replace the parameter 'to' by a function.
Bye
